services:
  postgres:
    image: postgres:18
    container_name: my_api_postgres2
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_volume2:/var/lib/postgresql

volumes:
  postgres_volume2:
