apiVersion: v1
kind: Pod                 # 오브젝트 종류 명시
metadata:
  name: my-nginx          # Pod 이름 (소문자, 하이픈만 허용)
  labels:
    app: nginx             # 나중에 Service가 이 Pod를 찾을 때 사용
spec:
  containers:
    - name: nginx            # 컨테이너 이름
      image: nginx:1.25      # Docker Hub,ECR 등 이미지
      ports:
        - containerPort: 80   # 컨테이너 안에서 열려 있는 포트

